title: My GitHub Learning Lab Blog
author: Jared Hampson
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is my blog for github learning lab

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  jhampson-dbre # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
